
build:
  version: "3.0"

cards:
  message: "Welcome to SihiBank accounts related local APIs "
  contactDetails:
    name: "Santhosh Kb - Developer"
    email: "santhoshkb@sihibank.com"
  onCallSupport:
    - (201) 100-100
    - (201) 100-101



