
build:
  version: "1.0"

cards:
  message: "Welcome to SihiBank accounts related Prod APIs "
  contactDetails:
    name: "Kush - Prod Support Lead"
    email: "kush@sihibank.com"
  onCallSupport:
    - (201) 100-300
    - (201) 100-301