
build:
  version: "2.0"

loans:
  message: "Welcome to SihiBank accounts related QA APIs "
  contactDetails:
    name: " Deepa Y - QA Lead"
    email: "deepay@sihibank.com"
  onCallSupport:
    - (201) 100-200
    - (201) 100-201