networks:
  sihibank-network:
    driver: "bridge"


services:

  configserver:
    image: "kbsanthosh/configserver:8.0.0-SNAPSHOT"
    container_name: configserver-rest-api
    ports:
      - "8071:8071"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8071/actuator/health/readiness | grep UP || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s # Essential: Gives the Spring Boot JVM time to warm up before counting failures
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "kbsanthosh/eurekaserver:8.0.0-SNAPSHOT"
    container_name: eurekaserver-rest-api
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: eurekaserver
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8070/actuator/health/readiness | grep UP || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s # Essential: Gives the Spring Boot JVM time to warm up before counting failures
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "kbsanthosh/accounts:8.0.0-SNAPSHOT"
    container_name: accounts-rest-api
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: accounts
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "kbsanthosh/loans:8.0.0-SNAPSHOT"
    container_name: loans-rest-api
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: loans
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "kbsanthosh/cards:8.0.0-SNAPSHOT"
    container_name: cards-rest-api
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: cards
    extends:
      file: common-config.yml
      service: microservice-configserver-config

